steps:
  - label: ':docker: Build'
    command: ./ci-scripts/build.sh
    artifact_paths: "bin/terraform-provider-mysql"

  - wait

  - label: ':docker: Push Image'
    command: ./ci-scripts/push-image.sh
    env:
      IMAGE_REPOSITORY: 278521702583.dkr.ecr.us-west-2.amazonaws.com/iops/terraform-provider-mysql
      IMAGE_TAG: "build-${BUILDKITE_BUILD_NUMBER}"